# Generated by Django 4.2 on 2023-04-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('email', models.EmailField(help_text='example@test.com', max_length=254, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, help_text='https://', null=True, verbose_name='سایت')),
                ('comment', models.TextField(verbose_name='کامنت')),
                ('date_sent', models.DateTimeField(verbose_name='تاریخ ارسال')),
                ('status', models.CharField(choices=[('read', 'خوانده شده'), ('unread', 'خوانده نشده')], default='unread', max_length=20, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
