# Generated by Django 4.2 on 2023-04-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlemodel_slug'),
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.articlemodel', verbose_name='مقاله'),
            preserve_default=False,
        ),
    ]
