# Generated by Django 4.2 on 2023-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, help_text='https:// | میتواند خالی بماند', null=True, verbose_name='سایت'),
        ),
    ]
