# Generated by Django 4.2 on 2023-04-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_articlemodel_options'),
        ('comment_app', '0003_alter_comment_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='blog_app.articlemodel', verbose_name='مقاله'),
        ),
    ]
