# Generated by Django 4.2 on 2023-04-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0004_alter_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_sent'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
