# Generated by Django 4.2 on 2023-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlemodel_slug'),
        ('tag_app', '0002_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
    ]
