# Generated by Django 4.2 on 2023-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0003_rename_tag_tagmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='slug',
            field=models.CharField(max_length=160, unique=True, verbose_name='اسلاک تگ'),
        ),
    ]
