# Generated by Django 4.2 on 2023-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_hash',
            field=models.CharField(default='', max_length=64, verbose_name='forget password hash'),
            preserve_default=False,
        ),
    ]
