# Generated by Django 4.2 on 2023-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_customuser_forget_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='forget_password_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='forget password hash'),
        ),
    ]
