# Generated by Django 4.2 on 2023-04-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='نام سایت')),
                ('site_address', models.URLField(verbose_name='آدرس سایت')),
                ('computer_logo', models.ImageField(help_text='72 * 394', upload_to='images/logos/', verbose_name='لوگوی سایت برای کامپیوتر')),
                ('mobile_logo', models.ImageField(help_text='56 * 202', upload_to='images/logos/', verbose_name='لوگوی سایت برای موبایل')),
                ('copy_right', models.CharField(max_length=250, verbose_name='متن کپی رایت')),
            ],
            options={
                'verbose_name': 'تظیم',
                'verbose_name_plural': 'اتتظیم',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شبکه')),
                ('url', models.URLField(verbose_name='لینک')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings_app.setting', verbose_name='تظیم')),
            ],
            options={
                'verbose_name': 'شبکه مجازی',
                'verbose_name_plural': 'شبکه های مجازی',
            },
        ),
    ]
