# Generated by Django 4.2 on 2023-04-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'تظیم', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socials', to='site_settings_app.setting', verbose_name='تظیم'),
        ),
    ]
