# Generated by Django 4.2 on 2023-05-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_app', '0002_alter_setting_options_alter_socialnetwork_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='short_icon',
            field=models.ImageField(default='', help_text='56 * 202', upload_to='images/logos/', verbose_name='شورت آیکن'),
            preserve_default=False,
        ),
    ]
