# Generated by Django 4.2 on 2023-04-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160, verbose_name='نام دسته بندی')),
                ('slug', models.TextField(max_length=160, verbose_name='اسلاک دسته بندی')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی ها',
            },
        ),
    ]
