# Generated by Django 4.2 on 2023-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlemodel_slug'),
        ('category_app', '0002_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
