# Generated by Django 4.2 on 2023-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_rename_category_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='images/category/', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
