# Generated by Django 4.2 on 2023-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_categorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.CharField(max_length=160, unique=True, verbose_name='اسلاک دسته بندی'),
        ),
    ]
