# Generated by Django 4.2 on 2023-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_alter_categorymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.CharField(default='', help_text='160 character | SEO', max_length=160, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='keywords',
            field=models.TextField(default='', help_text='با , از هم جدا کنید | SEO', verbose_name='کلمات کلیدی'),
            preserve_default=False,
        ),
    ]
