# Generated by Django 4.2 on 2023-04-04 14:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='ContactModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان تماس')),
                ('text', models.TextField(verbose_name='متن تماس')),
                ('date_sent', models.DateTimeField(verbose_name='تاریخ ارسال')),
                ('answre', models.TextField(verbose_name='جواب')),
                ('status', models.CharField(choices=[('read', 'جواب داد شده'), ('unread', 'جواب داد نشده')], default='unread', max_length=50, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس های کاربران',
            },
        ),
    ]
