# Generated by Django 4.2 on 2023-04-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'توضیح', 'verbose_name_plural': 'صفحه تماس با ما'},
        ),
    ]
