# Generated by Django 4.2 on 2023-04-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_alter_address_address_alter_email_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='content',
        ),
    ]
