# Generated by Django 4.2 on 2023-05-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_alter_articlemodel_tags'),
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepageads',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='blog_app.articlemodel', verbose_name='مقاله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepageads',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adses', to=settings.AUTH_USER_MODEL, verbose_name='سازنده تبلیغ'),
        ),
    ]
