# Generated by Django 4.2 on 2023-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0002_articlepageads_article_alter_articlepageads_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepageads',
            name='file',
            field=models.ImageField(help_text='نوع فایل: گیف', upload_to='files/ads/', verbose_name='فایل'),
        ),
    ]
