# Generated by Django 4.2 on 2023-05-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_articlemodel_tags'),
        ('about_app', '0002_aboutmodel_description_aboutmodel_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_app', '0007_contactmodel_description_contactmodel_keywords'),
        ('ads_app', '0003_alter_articlepageads_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepageads',
            options={'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات صفحه های مقاله ها'},
        ),
        migrations.AlterField(
            model_name='articlepageads',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_ads', to='blog_app.articlemodel', verbose_name='مقاله'),
        ),
        migrations.CreateModel(
            name='HomePageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(help_text='https://...', verbose_name='لینک')),
                ('file', models.ImageField(help_text='نوع فایل: گیف', upload_to='files/ads/', verbose_name='فایل')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('expiry_date', models.DateTimeField(verbose_name='تاریخ انقضاء')),
                ('pay', models.CharField(max_length=100, verbose_name='هزینه پرداختی')),
                ('active', models.BooleanField(verbose_name='فعال')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_adses', to=settings.AUTH_USER_MODEL, verbose_name='سازنده تبلیغ')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه خانه',
            },
        ),
        migrations.CreateModel(
            name='ContactPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(help_text='https://...', verbose_name='لینک')),
                ('file', models.ImageField(help_text='نوع فایل: گیف', upload_to='files/ads/', verbose_name='فایل')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('expiry_date', models.DateTimeField(verbose_name='تاریخ انقضاء')),
                ('pay', models.CharField(max_length=100, verbose_name='هزینه پرداختی')),
                ('active', models.BooleanField(verbose_name='فعال')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='contact_app.contactmodel', verbose_name='درباره ما')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_adses', to=settings.AUTH_USER_MODEL, verbose_name='سازنده تبلیغ')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه تماس ما',
            },
        ),
        migrations.CreateModel(
            name='AboutPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(help_text='https://...', verbose_name='لینک')),
                ('file', models.ImageField(help_text='نوع فایل: گیف', upload_to='files/ads/', verbose_name='فایل')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('expiry_date', models.DateTimeField(verbose_name='تاریخ انقضاء')),
                ('pay', models.CharField(max_length=100, verbose_name='هزینه پرداختی')),
                ('active', models.BooleanField(verbose_name='فعال')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='about_app.aboutmodel', verbose_name='درباره ما')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='about_adses', to=settings.AUTH_USER_MODEL, verbose_name='سازنده تبلیغ')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه درباره ما',
            },
        ),
    ]
