# Generated by Django 4.2 on 2023-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=150, verbose_name='کلمه')),
                ('search_count', models.BigIntegerField(default=0, verbose_name='تعداد سرچ')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('date_updated', models.DateTimeField(verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'نتیجه',
                'verbose_name_plural': 'نتایچ سرچ',
                'ordering': ['-date_updated'],
            },
        ),
    ]
