# Generated by Django 4.2 on 2023-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(help_text='مثال: article-name', max_length=160, unique=True, verbose_name='اسلاگ'),
        ),
    ]
