# Generated by Django 4.2 on 2023-04-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlemodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['-date_created'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
    ]
