# Generated by Django 4.2 on 2023-04-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0004_alter_tagmodel_slug'),
        ('blog_app', '0003_alter_articlemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='tag_app.tagmodel', verbose_name='تگ ها'),
        ),
    ]
