# Generated by Django 4.2 on 2023-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('date_joined', models.DateTimeField(verbose_name='تاریخ عضویت')),
                ('status', models.CharField(choices=[('subscribe', 'عضو شده'), ('unsubscribe', 'عضو نشده')], default='unsubscribe', max_length=50, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
                'ordering': ['-date_joined'],
            },
        ),
    ]
